---
- hosts: all
  vars:
  gather_facts: False
  tasks:
    - name: Install IIS
      win_feature:
          name: web-server
          include_management_tools: yes
          include_sub_features: yes
          state: present
  
    - name: Copy index.html to wwwroot
      win_copy:
        src: index.html
        dest: C:\inetpub\wwwroot\index.html
        force: yes
  
    - name: install net core iis hosting module with no frameworks
      win_chocolatey:
        name: "dotnetcore-windowshosting"
        version: "3.1.0"
        install_args: "OPT_NO_RUNTIME=1 OPT_NO_SHAREDFX=1 OPT_NO_X86=1 OPT_NO_SHARED_CONFIG_CHECK=1"
        state: present
      notify: restart IIS
  
    - name: Create logging directory
      win_file:
          path: c:\logs
          state: directory
  
    # - name: Induce an exception to see what happens
    #   win_ping:
    #     data: crash
  
  handlers:
    - name: restart IIS
      win_shell: '& {iisreset}'


